// The product resource
// 1. body_html
// => The description of the product which supports HTML formatting.

// 2. created_at
// => The date and time when the product was created.

// 3. handle
// => It is a unique human friendly string for the product which is automatically generated by the products title. (Used by liquid templating language to refer object)

// 4. id
// It is a unsigned 64 bit unique value which for the product. Each and every product id is unique. No product can have more than one id.

// 5. images
// It is the list of product image objects, each one representing an image associated with the product.

// 6. options
// It is a custom product property. Example: Size, Color and Material. Each product can have upto 3 options and each option can have 255 characters. Every option can have multiple value.

// 7. product_type
// Used for search and filtering products

// 8. published_at
// The date and time when the product was published. It could be set to null if the product have to be set unpublished.

// 9. published_scope
// Where the product was published to the Point of the sale channel. (pos is a place where transactions are made.) It's required values are:
// 1. web: The product is not published to Point of the sale channel.
// 2. global: The product is published to the point of the sale channel.

// 10. status
// It showed the status of the product. It's required values are:
// 1. active: The product is ready to sell and it is available to the customers available in the stores.
// 2. archived: The product is no longer available being sold and it is not available to the customers.
// 3. draft: The product are not yet ready to be sold and is not available to the customers. By default, duplicate and unarchived products are set to draft.

// 11. tags
// It is a comma separated list of tags that are used for filtering and searching. A product can have up to 250 tags. And each tag can have 255 characters.

// 12. template_suffix
// It is the suffix of the liquid template used for the product page. If this property is specified then the product page will use a template called "product.template.liquid". If this property is "" or null then the default template will be used which is "product.template".

// 13. title
// The name of the product

// 14. updated_at
// The date and time of the product when it was last modified

// 15. variants
// It is an array of product variants, each representing a different variant for the product. The position property is read-only. The position of variants is indicated by the order in which they are listed.

// 16. vendor
// The name of product vendor.